apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-data
spec:
  storageClassName: manual
  capacity: 
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Users/javierrodriguez/Documents/Repositorios/EcosistemaJenkins/kubernetesdata
    #path: /run/desktop/mnt/host/c/USERS/etc......